// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: kllla.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRegistrationCertificateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRegistrationCertificateRequest) Reset() {
	*x = GetRegistrationCertificateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kllla_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRegistrationCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistrationCertificateRequest) ProtoMessage() {}

func (x *GetRegistrationCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kllla_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegistrationCertificateRequest.ProtoReflect.Descriptor instead.
func (*GetRegistrationCertificateRequest) Descriptor() ([]byte, []int) {
	return file_kllla_proto_rawDescGZIP(), []int{0}
}

type GetRegistrationCertificateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cert []byte `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
}

func (x *GetRegistrationCertificateResponse) Reset() {
	*x = GetRegistrationCertificateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kllla_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRegistrationCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistrationCertificateResponse) ProtoMessage() {}

func (x *GetRegistrationCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kllla_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegistrationCertificateResponse.ProtoReflect.Descriptor instead.
func (*GetRegistrationCertificateResponse) Descriptor() ([]byte, []int) {
	return file_kllla_proto_rawDescGZIP(), []int{1}
}

func (x *GetRegistrationCertificateResponse) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

type RegistrationSignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Csr  []byte `protobuf:"bytes,2,opt,name=csr,proto3" json:"csr,omitempty"`
}

func (x *RegistrationSignRequest) Reset() {
	*x = RegistrationSignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kllla_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationSignRequest) ProtoMessage() {}

func (x *RegistrationSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kllla_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationSignRequest.ProtoReflect.Descriptor instead.
func (*RegistrationSignRequest) Descriptor() ([]byte, []int) {
	return file_kllla_proto_rawDescGZIP(), []int{2}
}

func (x *RegistrationSignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistrationSignRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

type RegistrationSignResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSigned bool   `protobuf:"varint,1,opt,name=is_signed,json=isSigned,proto3" json:"is_signed,omitempty"`
	Cert     []byte `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
}

func (x *RegistrationSignResponse) Reset() {
	*x = RegistrationSignResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kllla_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationSignResponse) ProtoMessage() {}

func (x *RegistrationSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kllla_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationSignResponse.ProtoReflect.Descriptor instead.
func (*RegistrationSignResponse) Descriptor() ([]byte, []int) {
	return file_kllla_proto_rawDescGZIP(), []int{3}
}

func (x *RegistrationSignResponse) GetIsSigned() bool {
	if x != nil {
		return x.IsSigned
	}
	return false
}

func (x *RegistrationSignResponse) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

type InitTokenHandshakeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *InitTokenHandshakeRequest) Reset() {
	*x = InitTokenHandshakeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kllla_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitTokenHandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitTokenHandshakeRequest) ProtoMessage() {}

func (x *InitTokenHandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kllla_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitTokenHandshakeRequest.ProtoReflect.Descriptor instead.
func (*InitTokenHandshakeRequest) Descriptor() ([]byte, []int) {
	return file_kllla_proto_rawDescGZIP(), []int{4}
}

func (x *InitTokenHandshakeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InitTokenHandshakeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encrypted string `protobuf:"bytes,1,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
}

func (x *InitTokenHandshakeResponse) Reset() {
	*x = InitTokenHandshakeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kllla_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitTokenHandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitTokenHandshakeResponse) ProtoMessage() {}

func (x *InitTokenHandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kllla_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitTokenHandshakeResponse.ProtoReflect.Descriptor instead.
func (*InitTokenHandshakeResponse) Descriptor() ([]byte, []int) {
	return file_kllla_proto_rawDescGZIP(), []int{5}
}

func (x *InitTokenHandshakeResponse) GetEncrypted() string {
	if x != nil {
		return x.Encrypted
	}
	return ""
}

type CompleteTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decrypted string `protobuf:"bytes,1,opt,name=decrypted,proto3" json:"decrypted,omitempty"`
}

func (x *CompleteTokenRequest) Reset() {
	*x = CompleteTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kllla_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTokenRequest) ProtoMessage() {}

func (x *CompleteTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kllla_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTokenRequest.ProtoReflect.Descriptor instead.
func (*CompleteTokenRequest) Descriptor() ([]byte, []int) {
	return file_kllla_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteTokenRequest) GetDecrypted() string {
	if x != nil {
		return x.Decrypted
	}
	return ""
}

type CompleteTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CompleteTokenResponse) Reset() {
	*x = CompleteTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kllla_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTokenResponse) ProtoMessage() {}

func (x *CompleteTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kllla_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTokenResponse.ProtoReflect.Descriptor instead.
func (*CompleteTokenResponse) Descriptor() ([]byte, []int) {
	return file_kllla_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type IsTokenValidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *IsTokenValidRequest) Reset() {
	*x = IsTokenValidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kllla_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsTokenValidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsTokenValidRequest) ProtoMessage() {}

func (x *IsTokenValidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kllla_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsTokenValidRequest.ProtoReflect.Descriptor instead.
func (*IsTokenValidRequest) Descriptor() ([]byte, []int) {
	return file_kllla_proto_rawDescGZIP(), []int{8}
}

func (x *IsTokenValidRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type IsTokenValidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *IsTokenValidResponse) Reset() {
	*x = IsTokenValidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kllla_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsTokenValidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsTokenValidResponse) ProtoMessage() {}

func (x *IsTokenValidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kllla_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsTokenValidResponse.ProtoReflect.Descriptor instead.
func (*IsTokenValidResponse) Descriptor() ([]byte, []int) {
	return file_kllla_proto_rawDescGZIP(), []int{9}
}

func (x *IsTokenValidResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type ShortenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shorten string `protobuf:"bytes,1,opt,name=shorten,proto3" json:"shorten,omitempty"`
}

func (x *ShortenRequest) Reset() {
	*x = ShortenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kllla_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequest) ProtoMessage() {}

func (x *ShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kllla_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequest.ProtoReflect.Descriptor instead.
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return file_kllla_proto_rawDescGZIP(), []int{10}
}

func (x *ShortenRequest) GetShorten() string {
	if x != nil {
		return x.Shorten
	}
	return ""
}

type ShortenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shortened string `protobuf:"bytes,2,opt,name=shortened,proto3" json:"shortened,omitempty"`
}

func (x *ShortenResponse) Reset() {
	*x = ShortenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kllla_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponse) ProtoMessage() {}

func (x *ShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kllla_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponse.ProtoReflect.Descriptor instead.
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return file_kllla_proto_rawDescGZIP(), []int{11}
}

func (x *ShortenResponse) GetShortened() string {
	if x != nil {
		return x.Shortened
	}
	return ""
}

var File_kllla_proto protoreflect.FileDescriptor

var file_kllla_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6b, 0x6c, 0x6c, 0x6c, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6b,
	0x6c, 0x6c, 0x6c, 0x61, 0x22, 0x23, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x22, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63,
	0x65, 0x72, 0x74, 0x22, 0x3f, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x73, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x63, 0x73, 0x72, 0x22, 0x4b, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x65, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x65, 0x72,
	0x74, 0x22, 0x2f, 0x0a, 0x19, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x48, 0x61,
	0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x1a, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x48,
	0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x22, 0x34,
	0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x65, 0x64, 0x22, 0x2d, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x2b, 0x0a, 0x13, 0x49, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x2c, 0x0a, 0x14, 0x49, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x2a,
	0x0a, 0x0e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x22, 0x2f, 0x0a, 0x0f, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x32, 0xe1, 0x01, 0x0a, 0x13,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x73, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x12, 0x28, 0x2e, 0x6b, 0x6c, 0x6c, 0x6c, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6b, 0x6c,
	0x6c, 0x6c, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x43, 0x41, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x53, 0x52, 0x12, 0x1e, 0x2e, 0x6b,
	0x6c, 0x6c, 0x6c, 0x61, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6b,
	0x6c, 0x6c, 0x6c, 0x61, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32,
	0x87, 0x02, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x59, 0x0a, 0x12, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x48, 0x61, 0x6e,
	0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x12, 0x20, 0x2e, 0x6b, 0x6c, 0x6c, 0x6c, 0x61, 0x2e, 0x49,
	0x6e, 0x69, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6b, 0x6c, 0x6c, 0x6c, 0x61,
	0x2e, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68,
	0x61, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x16, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x48, 0x61, 0x6e, 0x64,
	0x73, 0x68, 0x61, 0x6b, 0x65, 0x12, 0x1b, 0x2e, 0x6b, 0x6c, 0x6c, 0x6c, 0x61, 0x2e, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6b, 0x6c, 0x6c, 0x6c, 0x61, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x47, 0x0a, 0x0c, 0x49, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x12, 0x1a, 0x2e, 0x6b, 0x6c, 0x6c, 0x6c, 0x61, 0x2e, 0x49, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6b,
	0x6c, 0x6c, 0x6c, 0x61, 0x2e, 0x49, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x4a, 0x0a, 0x0e, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x12, 0x15, 0x2e, 0x6b, 0x6c, 0x6c, 0x6c, 0x61, 0x2e, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x6b, 0x6c, 0x6c, 0x6c, 0x61, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_kllla_proto_rawDescOnce sync.Once
	file_kllla_proto_rawDescData = file_kllla_proto_rawDesc
)

func file_kllla_proto_rawDescGZIP() []byte {
	file_kllla_proto_rawDescOnce.Do(func() {
		file_kllla_proto_rawDescData = protoimpl.X.CompressGZIP(file_kllla_proto_rawDescData)
	})
	return file_kllla_proto_rawDescData
}

var file_kllla_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_kllla_proto_goTypes = []interface{}{
	(*GetRegistrationCertificateRequest)(nil),  // 0: kllla.GetRegistrationCertificateRequest
	(*GetRegistrationCertificateResponse)(nil), // 1: kllla.GetRegistrationCertificateResponse
	(*RegistrationSignRequest)(nil),            // 2: kllla.RegistrationSignRequest
	(*RegistrationSignResponse)(nil),           // 3: kllla.RegistrationSignResponse
	(*InitTokenHandshakeRequest)(nil),          // 4: kllla.InitTokenHandshakeRequest
	(*InitTokenHandshakeResponse)(nil),         // 5: kllla.InitTokenHandshakeResponse
	(*CompleteTokenRequest)(nil),               // 6: kllla.CompleteTokenRequest
	(*CompleteTokenResponse)(nil),              // 7: kllla.CompleteTokenResponse
	(*IsTokenValidRequest)(nil),                // 8: kllla.IsTokenValidRequest
	(*IsTokenValidResponse)(nil),               // 9: kllla.IsTokenValidResponse
	(*ShortenRequest)(nil),                     // 10: kllla.ShortenRequest
	(*ShortenResponse)(nil),                    // 11: kllla.ShortenResponse
}
var file_kllla_proto_depIdxs = []int32{
	0,  // 0: kllla.RegistrationService.GetRegistrationCertificate:input_type -> kllla.GetRegistrationCertificateRequest
	2,  // 1: kllla.RegistrationService.RequestCASignCSR:input_type -> kllla.RegistrationSignRequest
	4,  // 2: kllla.TokenService.InitTokenHandshake:input_type -> kllla.InitTokenHandshakeRequest
	6,  // 3: kllla.TokenService.CompleteTokenHandshake:input_type -> kllla.CompleteTokenRequest
	8,  // 4: kllla.TokenService.IsTokenValid:input_type -> kllla.IsTokenValidRequest
	10, // 5: kllla.ShortenService.Shorten:input_type -> kllla.ShortenRequest
	1,  // 6: kllla.RegistrationService.GetRegistrationCertificate:output_type -> kllla.GetRegistrationCertificateResponse
	3,  // 7: kllla.RegistrationService.RequestCASignCSR:output_type -> kllla.RegistrationSignResponse
	5,  // 8: kllla.TokenService.InitTokenHandshake:output_type -> kllla.InitTokenHandshakeResponse
	7,  // 9: kllla.TokenService.CompleteTokenHandshake:output_type -> kllla.CompleteTokenResponse
	9,  // 10: kllla.TokenService.IsTokenValid:output_type -> kllla.IsTokenValidResponse
	11, // 11: kllla.ShortenService.Shorten:output_type -> kllla.ShortenResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_kllla_proto_init() }
func file_kllla_proto_init() {
	if File_kllla_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kllla_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRegistrationCertificateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kllla_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRegistrationCertificateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kllla_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationSignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kllla_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationSignResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kllla_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitTokenHandshakeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kllla_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitTokenHandshakeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kllla_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kllla_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kllla_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsTokenValidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kllla_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsTokenValidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kllla_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kllla_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kllla_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_kllla_proto_goTypes,
		DependencyIndexes: file_kllla_proto_depIdxs,
		MessageInfos:      file_kllla_proto_msgTypes,
	}.Build()
	File_kllla_proto = out.File
	file_kllla_proto_rawDesc = nil
	file_kllla_proto_goTypes = nil
	file_kllla_proto_depIdxs = nil
}
